services:
  api:
    build:
      context: ./api-scrabble
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./scrabble
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
